#!/usr/bin/env bash
# Dyuti OS APT repository — configuration.
# This is your update/security backbone. Host the published tree on an
# India-based server (sovereignty + speed). Sign everything with your own key.

export REPO_NAME="dyuti-stable"
export REPO_DIST="stable"
export REPO_COMPONENT="main"
export REPO_ARCHS="amd64"

# Signing identity (the key is generated by setup-repo.sh if absent).
export GPG_NAME="Dyuti OS Archive Signing Key"
export GPG_EMAIL="archive@example.in"

# Where aptly keeps its database + published tree.
export APTLY_ROOT="${APTLY_ROOT:-$HOME/.aptly}"

# Public URL where the published tree will be served (set to your India server).
#   e.g. https://repo.dyuti.in/dyuti
export REPO_PUBLIC_URL="${REPO_PUBLIC_URL:-https://repo.example.in/dyuti}"

# Exported public key lives here (shipped to clients in the keyring package).
export KEYS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/keys"
